m<-matrix(c(1:10),nrow=5,ncol=4)
print(m)
ma<-apply(m,2,sum)
print(ma)
print(typeof(ma))
df<-data.frame(x=1,y=5:8,z=10:13)
print(df)
print(apply(X=df,MARGIN=1,FUN=sum))
print(lapply(df,sum))
name<-c("vikas","mohan","rugved")
print(lapply(name,toupper))
print(sapply(df,sum))
print(sapply(name,toupper))
      