install.packages("reshape")
library(reshape)
country<- data.frame(c("A","B","C"),c(200,300,100),c(2000,4000,3000))
colnames(country)<-c("Countries","Population","GDP")
print(country)
country_w<-melt(country,id.vars = c("Countries"))
print(country_w)
install.packages("reshape2")
library(reshape2)
country_L<-dcast(country_w,Countries~variable,sum)
print(country_L)
library(tidyr)
country_long<-gather(country,detail,value,Population:GDP,factor_key = TRUE)
print(country_long)
country_wide<-spread(country_long,detail,value)
print(country_wide)
