names<-c("heena","joyti","kiran","shivani")
print(names)
print(typeof(names))
n<-c(78,'hina',89,90)
print(n)
print(typeof(n))
d<-c(45.5,82.2,'dip','karan')
print(typeof(d))
print(d)
b=c("True","False")
print(b)
print(typeof(b))
num<-2:20
print(typeof(num))
print(num)
print(length(names))
print(sort(names))
print(sort(names,decreasing=TRUE))
print(names[0]) #Slicing
print(names[1])
print(names[c(2,4)])
print(names[c(-3)])
print(names[c(-2,-4)])
names[1]="udit" #adding
print(names)
names[5]="priya"
print(names)
a<-c(2,5,6)
b<-c(3,5,6)
z<-a+b
print(z)
y<-a-b
print(y)
x<-a*b
print(x)
w<-a/b
print(w)
e<-c(2,4,5,6,8)#vector add
s<-e+10
print(s)
p<-e*2
print(p)
s<-rep(c(2,4,6),each=4)
print(s)
s<-rep(c(2,4,6),times=4)
print(s)
s<-rep(c(3,5,7),times=c(3,2,1))
print(s)
s<-seq(from=10,to=100,by=10)
print(s)
s<-NULL
print(s)
assign("n",c(5,6,8,3,12))
print(n)
print(is.numeric(n))
print(is.integer(n))
print(is.character(n))
print(is.logical(n))


